# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weibo_analyse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from time import sleep

import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from code.analyse import AC_
from code.request import content_text_, get_user, get_hot_
from code.send_weibo import get_cookie, send_weibo
from visual import key_, emo_, hot_, user_


class Ui_weibo_analyse(object):
    def setupUi(self, weibo_analyse):
        weibo_analyse.setObjectName("weibo_analyse")
        weibo_analyse.resize(1032, 741)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../other/pic/微博.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        weibo_analyse.setWindowIcon(icon)
        weibo_analyse.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(weibo_analyse)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1061, 691))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_5.setAutoFillBackground(True)
        self.tab_5.setStyleSheet("")
        self.tab_5.setObjectName("tab_5")
        self.text_login = QtWidgets.QPushButton(self.tab_5)
        self.text_login.setGeometry(QtCore.QRect(450, 340, 151, 61))
        self.text_login.setAutoFillBackground(False)
        self.text_login.setStyleSheet("font: 15pt \"华文彩云\";\n"
                                      "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../other/pic/扫一扫.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.text_login.setIcon(icon1)
        self.text_login.setIconSize(QtCore.QSize(25, 25))
        self.text_login.setObjectName("text_login")
        self.listView_5 = QtWidgets.QListView(self.tab_5)
        self.listView_5.setGeometry(QtCore.QRect(0, 0, 1071, 691))
        self.listView_5.setStyleSheet("border-image: url(:/jpg/back2.jpg);")
        self.listView_5.setObjectName("listView_5")
        self.listView_5.raise_()
        self.text_login.raise_()
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.but_search_key = QtWidgets.QPushButton(self.tab)
        self.but_search_key.setGeometry(QtCore.QRect(230, 20, 91, 31))
        self.but_search_key.setStyleSheet("font: 11pt \"微软雅黑\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../other/pic/查看 搜索.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_search_key.setIcon(icon2)
        self.but_search_key.setIconSize(QtCore.QSize(20, 20))
        self.but_search_key.setObjectName("but_search_key")
        self.word_key = QtWidgets.QLineEdit(self.tab)
        self.word_key.setGeometry(QtCore.QRect(30, 20, 201, 31))
        self.word_key.setObjectName("word_key")
        self.look_frequency = QtWidgets.QPushButton(self.tab)
        self.look_frequency.setGeometry(QtCore.QRect(340, 280, 371, 51))
        self.look_frequency.setStyleSheet("font: 11pt \"微软雅黑\";")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../other/pic/分析.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.look_frequency.setIcon(icon3)
        self.look_frequency.setIconSize(QtCore.QSize(25, 25))
        self.look_frequency.setObjectName("look_frequency")
        self.look_emo = QtWidgets.QPushButton(self.tab)
        self.look_emo.setGeometry(QtCore.QRect(340, 350, 371, 51))
        self.look_emo.setStyleSheet("font: 11pt \"微软雅黑\";")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../other/pic/情感.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.look_emo.setIcon(icon4)
        self.look_emo.setIconSize(QtCore.QSize(25, 25))
        self.look_emo.setObjectName("look_emo")
        self.word_keyss = QtWidgets.QLineEdit(self.tab)
        self.word_keyss.setGeometry(QtCore.QRect(340, 210, 241, 41))
        self.word_keyss.setObjectName("word_keyss")
        self.but_search_lists = QtWidgets.QPushButton(self.tab)
        self.but_search_lists.setGeometry(QtCore.QRect(580, 210, 131, 41))
        self.but_search_lists.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.but_search_lists.setIcon(icon2)
        self.but_search_lists.setIconSize(QtCore.QSize(25, 25))
        self.but_search_lists.setObjectName("but_search_lists")
        self.listView_2 = QtWidgets.QListView(self.tab)
        self.listView_2.setGeometry(QtCore.QRect(0, 0, 1071, 691))
        self.listView_2.setStyleSheet("border-image: url(:/jpg/back2.jpg);")
        self.listView_2.setObjectName("listView_2")
        self.listView_2.raise_()
        self.but_search_key.raise_()
        self.word_key.raise_()
        self.look_frequency.raise_()
        self.look_emo.raise_()
        self.word_keyss.raise_()
        self.but_search_lists.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.but_search_user = QtWidgets.QPushButton(self.tab_2)
        self.but_search_user.setGeometry(QtCore.QRect(580, 230, 93, 31))
        self.but_search_user.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.but_search_user.setIcon(icon2)
        self.but_search_user.setIconSize(QtCore.QSize(20, 20))
        self.but_search_user.setObjectName("but_search_user")
        self.user_id = QtWidgets.QLineEdit(self.tab_2)
        self.user_id.setGeometry(QtCore.QRect(330, 230, 251, 31))
        self.user_id.setObjectName("user_id")
        self.but_user_analyse = QtWidgets.QPushButton(self.tab_2)
        self.but_user_analyse.setGeometry(QtCore.QRect(330, 300, 341, 91))
        self.but_user_analyse.setStyleSheet("font: 11pt \"微软雅黑\";")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../other/pic/分析2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_user_analyse.setIcon(icon5)
        self.but_user_analyse.setIconSize(QtCore.QSize(25, 25))
        self.but_user_analyse.setObjectName("but_user_analyse")
        self.listView_3 = QtWidgets.QListView(self.tab_2)
        self.listView_3.setGeometry(QtCore.QRect(0, 0, 1071, 691))
        self.listView_3.setStyleSheet("border-image: url(:/jpg/back2.jpg);")
        self.listView_3.setObjectName("listView_3")
        self.listView_3.raise_()
        self.but_search_user.raise_()
        self.user_id.raise_()
        self.but_user_analyse.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.but_get_hot = QtWidgets.QPushButton(self.tab_3)
        self.but_get_hot.setGeometry(QtCore.QRect(30, 30, 93, 28))
        self.but_get_hot.setStyleSheet("font: 11pt \"微软雅黑\";")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../other/pic/刷新.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_get_hot.setIcon(icon6)
        self.but_get_hot.setObjectName("but_get_hot")
        self.but_hot_analyse = QtWidgets.QPushButton(self.tab_3)
        self.but_hot_analyse.setGeometry(QtCore.QRect(120, 30, 93, 28))
        self.but_hot_analyse.setStyleSheet("font: 11pt \"微软雅黑\";")
        self.but_hot_analyse.setIcon(icon5)
        self.but_hot_analyse.setObjectName("but_hot_analyse")
        self.listView_4 = QtWidgets.QListView(self.tab_3)
        self.listView_4.setGeometry(QtCore.QRect(0, 0, 1071, 691))
        self.listView_4.setStyleSheet("border-image: url(:/jpg/back2.jpg);")
        self.listView_4.setObjectName("listView_4")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(320, 30, 361, 621))
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.listView_4.raise_()
        self.but_get_hot.raise_()
        self.but_hot_analyse.raise_()
        self.textEdit.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.attack_key = QtWidgets.QLineEdit(self.tab_4)
        self.attack_key.setGeometry(QtCore.QRect(530, 210, 141, 41))
        self.attack_key.setObjectName("attack_key")
        self.attack_num = QtWidgets.QSpinBox(self.tab_4)
        self.attack_num.setGeometry(QtCore.QRect(530, 350, 141, 41))
        self.attack_num.setObjectName("attack_num")
        self.attack_emo = QtWidgets.QComboBox(self.tab_4)
        self.attack_emo.setGeometry(QtCore.QRect(530, 280, 141, 41))
        self.attack_emo.setObjectName("attack_emo")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(370, 210, 121, 41))
        self.label.setStyleSheet("font: 12pt \"方正粗黑宋简体\";\n"
                                 "color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(370, 290, 121, 31))
        self.label_2.setStyleSheet("font: 12pt \"方正粗黑宋简体\";\n"
                                   "color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(370, 360, 131, 31))
        self.label_3.setStyleSheet("font: 12pt \"方正粗黑宋简体\";\n"
                                   "color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.but_pushButton = QtWidgets.QPushButton(self.tab_4)
        self.but_pushButton.setGeometry(QtCore.QRect(370, 420, 301, 41))
        self.but_pushButton.setStyleSheet("font: 15pt \"华文彩云\";\n"
                                          "")
        self.but_pushButton.setObjectName("but_pushButton")
        self.listView_6 = QtWidgets.QListView(self.tab_4)
        self.listView_6.setGeometry(QtCore.QRect(0, 0, 1071, 691))
        self.listView_6.setStyleSheet("border-image: url(:/jpg/back2.jpg);")
        self.listView_6.setObjectName("listView_6")
        self.listView_6.raise_()
        self.attack_key.raise_()
        self.attack_num.raise_()
        self.attack_emo.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.but_pushButton.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        weibo_analyse.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(weibo_analyse)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 29))
        self.menubar.setObjectName("menubar")
        weibo_analyse.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(weibo_analyse)
        self.statusbar.setObjectName("statusbar")
        weibo_analyse.setStatusBar(self.statusbar)

        self.retranslateUi(weibo_analyse)
        self.tabWidget.setCurrentIndex(3)
        self.text_login.clicked.connect(self.login)
        self.but_search_key.clicked.connect(self.search_key)
        self.but_search_lists.clicked.connect(self.search_list)
        self.look_frequency.clicked.connect(self.key_frequency)
        self.look_emo.clicked.connect(self.key_emo)
        self.but_search_user.clicked.connect(self.search_user)
        self.but_user_analyse.clicked.connect(self.analyse_user)
        self.but_get_hot.clicked.connect(self.get_hot)
        self.but_hot_analyse.clicked.connect(self.hot_analyse)
        self.but_pushButton.clicked.connect(self.attack)
        QtCore.QMetaObject.connectSlotsByName(weibo_analyse)

    def retranslateUi(self, weibo_analyse):
        _translate = QtCore.QCoreApplication.translate
        weibo_analyse.setWindowTitle(_translate("weibo_analyse", "微博数据爬取与分析系统"))
        self.text_login.setText(_translate("weibo_analyse", "登录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("weibo_analyse", "登录"))
        self.but_search_key.setText(_translate("weibo_analyse", "关键字"))
        self.look_frequency.setText(_translate("weibo_analyse", "词频"))
        self.look_emo.setText(_translate("weibo_analyse", "情感"))
        self.but_search_lists.setText(_translate("weibo_analyse", "搜索指定词"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("weibo_analyse", "关键字"))
        self.but_search_user.setText(_translate("weibo_analyse", "搜索"))
        self.but_user_analyse.setText(_translate("weibo_analyse", "分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("weibo_analyse", "用户"))
        self.but_get_hot.setText(_translate("weibo_analyse", "刷新"))
        self.but_hot_analyse.setText(_translate("weibo_analyse", "对比"))
        self.textEdit.setHtml(_translate("weibo_analyse",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">刷新后显示热搜榜</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("weibo_analyse", "热搜"))
        self.label.setText(_translate("weibo_analyse", "请输入关键字"))
        self.label_2.setText(_translate("weibo_analyse", "选择情感倾向"))
        self.label_3.setText(_translate("weibo_analyse", "选择发博条数"))
        self.but_pushButton.setText(_translate("weibo_analyse", "确认发送"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("weibo_analyse", "水军攻击"))
        self.attack_emo.addItems(["正面", "负面"])

    def login(self):
        QMessageBox.about(None, '提示', '您有50s时间扫码登录，请抓紧时间')
        get_cookie()
        QMessageBox.about(None, '提示', '登录成功')

    def search_key(self):
        print("key")
        print(self.word_key.text())
        key = self.word_key.text()
        QMessageBox.about(None, '提示', '正在爬取内容，请稍后')
        content_text_(key)
        QMessageBox.about(None, '提示', '内容爬取完成，可进行分析')

    def search_list(self):
        print("hi")
        list0 = self.word_keyss.text()
        print(list0)
        print(type(list0))
        list_ = list0.split("，")
        print(type(list_))
        print(list_)
        lines=AC_(list_)
        string=''
        num=1
        for line in lines:
            string=string+str(num)+": "+line+"\n"
            num=num+1
        QMessageBox.about(None,'结果','您的搜索结果为:\n'+string)


    def key_frequency(self):
        QMessageBox.about(None, '提示', '正在分析中')
        key_()

    def key_emo(self):
        QMessageBox.about(None, '提示', '正在分析中')
        emo_()

    def search_user(self):
        id=self.user_id.text()
        QMessageBox.about(None, '提示', '正在获取用户数据')
        get_user(id)
        QMessageBox.about(None, '提示', '用户数据获取完成，可进行分析')

    def analyse_user(self):
        user_()

    def get_hot(self):
        get_hot_()
        print("end get")
        sleep(5)
        data = pd.read_csv('../other/test_data/hot5.csv')
        title = data['hot_title']
        print(title)
        lines = ''
        for i in range(len(title)):
            line = str(i+1) + "  " + title[i]
            lines = lines + line + "\n"
        self.textEdit.setPlainText(lines)

    def hot_analyse(self):
        hot_()

    def attack(self):
        key = self.attack_key.text()
        emo = self.attack_emo.currentText()
        if emo == "正面":
            emo = 1
        elif emo == "负面":
            emo = -1
        num = self.attack_num.value()
        print(type(key), type(emo), type(num))
        QMessageBox.about(None, '提示', '正在发送中，请稍后')
        print(key, end=' ')
        print(emo, end=' ')
        print(num, end=' ')
        send_weibo(key,emo,num)
        QMessageBox.about(None, '提示', '指定微博发送完成')

import other.pic.img_rc

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    # MainWindow =Ui_weibo_analyse()
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_weibo_analyse()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
